# Generated by Django 6.0 on 2025-12-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_remove_doctor_image_url_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='accepted_insurances',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='doctor',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='practice_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
