# Generated by Django 6.0 on 2025-12-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctor_address_doctor_license_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='licenses/'),
        ),
    ]
