# Generated by Django 6.0 on 2025-12-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_doctor_license_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorschedule',
            options={'ordering': ['day_of_week', 'start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='doctorschedule',
            unique_together=set(),
        ),
    ]
