# Generated by Django 6.0 on 2025-12-13 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_alter_doctorschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorschedule',
            unique_together={('doctor', 'day_of_week', 'start_time')},
        ),
    ]
